version: '3.8'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "5173:5173"
    volumes:
      - ../web:/app
    depends_on:
      - api
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "3001:3001"
    volumes:
      - ../api:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: senha_super_segura
      POSTGRES_DB: financeiro
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
